version: "3"

services:
  nginx-gateway:
    image: nginx:1.21.5
    container_name: nginx-gateway
    restart: always
    privileged: true
    environment:
      - TZ=Africa/Tunis
    ports:
      - 8888:8081
    volumes:
      - ./deploy/nginx/conf.d:/etc/nginx/conf.d
      - ./data/nginx/log:/var/log/nginx
    networks:
      - looklook_net
    depends_on:
      - looklook

  looklook:
    # docker-hub : https://hub.docker.com/r/lyumikael/gomodd
    # dockerfile: https://github.com/Mikaelemmmm/gomodd , If you are macOs m1\m2 use dockerfile yourself to build the image
    image: lyumikael/gomodd:v1.20.3
    container_name: looklook
    environment:
      TZ: Africa/Tunis
      GOPROXY: https://goproxy.cn,direct
    working_dir: /go/looklook
    volumes:
      - .:/go/looklook
    privileged: true
    restart: always
    networks:
      - looklook_net

networks:
  looklook_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
