apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: retro-station
build:
  artifacts:
    # image tags are relative; to specify an image repo (e.g. GCR), you
    # must provide a "default repo" using one of the methods described
    # here:
    # https://skaffold.dev/docs/concepts/#image-repository-handling
    - image: emailservice
      context: src/emailservice
    - image: productcatalogservice
      context: src/productcatalogservice
    - image: recommendationservice
      context: src/recommendationservice
    - image: shippingservice
      context: src/shippingservice
    - image: checkoutservice
      context: src/checkoutservice
    - image: paymentservice
      context: src/paymentservice
    - image: currencyservice
      context: src/currencyservice
    - image: cartservice
      context: src/cartservice
      docker:
        dockerfile: Dockerfile
    - image: frontend
      context: src/frontend
  tagPolicy:
    gitCommit: {}
  local:
    useBuildkit: false
    concurrency: 10
deploy:
  kubectl:
    manifests:
      - ./kubernetes-manifests/cartservice.yaml
      - ./kubernetes-manifests/checkoutservice.yaml
      - ./kubernetes-manifests/currencyservice.yaml
      - ./kubernetes-manifests/emailservice.yaml
      - ./kubernetes-manifests/frontend.yaml
      - ./kubernetes-manifests/paymentservice.yaml
      - ./kubernetes-manifests/productcatalogservice.yaml
      - ./kubernetes-manifests/recommendationservice.yaml
      - ./kubernetes-manifests/shippingservice.yaml
      - ./kubernetes-manifests/gomicro.yaml

---
apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: loadgenerator
requires:
  - configs: [retro-station]
build:
  artifacts:
    - image: loadgenerator
      context: src/loadgenerator
deploy:
  kubectl:
    manifests:
      - ./kubernetes-manifests/loadgenerator.yaml
