// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	pipeline "github.com/zizouhuweidi/retro-station/internal/pkg/messaging/pipeline"

	types "github.com/zizouhuweidi/retro-station/internal/pkg/messaging/types"
)

// ConsumerPipeline is an autogenerated mock type for the ConsumerPipeline type
type ConsumerPipeline struct {
	mock.Mock
}

// Handle provides a mock function with given fields: ctx, consumerContext, next
func (_m *ConsumerPipeline) Handle(ctx context.Context, consumerContext types.MessageConsumeContext, next pipeline.ConsumerHandlerFunc) error {
	ret := _m.Called(ctx, consumerContext, next)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.MessageConsumeContext, pipeline.ConsumerHandlerFunc) error); ok {
		r0 = rf(ctx, consumerContext, next)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewConsumerPipeline creates a new instance of ConsumerPipeline. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConsumerPipeline(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConsumerPipeline {
	mock := &ConsumerPipeline{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
