// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	pipeline "github.com/zizouhuweidi/retro-station/internal/pkg/messaging/pipeline"
)

// ConsumerPipelineConfigurationBuilderFunc is an autogenerated mock type for the ConsumerPipelineConfigurationBuilderFunc type
type ConsumerPipelineConfigurationBuilderFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *ConsumerPipelineConfigurationBuilderFunc) Execute(_a0 pipeline.ConsumerPipelineConfigurationBuilder) {
	_m.Called(_a0)
}

// NewConsumerPipelineConfigurationBuilderFunc creates a new instance of ConsumerPipelineConfigurationBuilderFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConsumerPipelineConfigurationBuilderFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConsumerPipelineConfigurationBuilderFunc {
	mock := &ConsumerPipelineConfigurationBuilderFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
