// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	consumer "github.com/zizouhuweidi/retro-station/internal/pkg/messaging/consumer"
)

// ConsumerHandlerConfigurationBuilderFunc is an autogenerated mock type for the ConsumerHandlerConfigurationBuilderFunc type
type ConsumerHandlerConfigurationBuilderFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *ConsumerHandlerConfigurationBuilderFunc) Execute(_a0 consumer.ConsumerHandlerConfigurationBuilder) {
	_m.Called(_a0)
}

// NewConsumerHandlerConfigurationBuilderFunc creates a new instance of ConsumerHandlerConfigurationBuilderFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConsumerHandlerConfigurationBuilderFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConsumerHandlerConfigurationBuilderFunc {
	mock := &ConsumerHandlerConfigurationBuilderFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
