// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ConsumerBuilderFucT is an autogenerated mock type for the ConsumerBuilderFucT type
type ConsumerBuilderFucT[T interface{}] struct {
	mock.Mock
}

// Execute provides a mock function with given fields: builder
func (_m *ConsumerBuilderFucT[T]) Execute(builder T) {
	_m.Called(builder)
}

// NewConsumerBuilderFucT creates a new instance of ConsumerBuilderFucT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConsumerBuilderFucT[T interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *ConsumerBuilderFucT[T] {
	mock := &ConsumerBuilderFucT[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
