// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	types "github.com/zizouhuweidi/retro-station/internal/pkg/messaging/types"
)

// ConsumerHandler is an autogenerated mock type for the ConsumerHandler type
type ConsumerHandler struct {
	mock.Mock
}

// Handle provides a mock function with given fields: ctx, consumeContext
func (_m *ConsumerHandler) Handle(ctx context.Context, consumeContext types.MessageConsumeContext) error {
	ret := _m.Called(ctx, consumeContext)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.MessageConsumeContext) error); ok {
		r0 = rf(ctx, consumeContext)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewConsumerHandler creates a new instance of ConsumerHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConsumerHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConsumerHandler {
	mock := &ConsumerHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
