// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	consumer "github.com/zizouhuweidi/retro-station/internal/pkg/messaging/consumer"

	types "github.com/zizouhuweidi/retro-station/internal/pkg/messaging/types"
)

// ConsumerConnector is an autogenerated mock type for the ConsumerConnector type
type ConsumerConnector struct {
	mock.Mock
}

// ConnectConsumer provides a mock function with given fields: messageType, _a1
func (_m *ConsumerConnector) ConnectConsumer(messageType types.IMessage, _a1 consumer.Consumer) error {
	ret := _m.Called(messageType, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ConnectConsumer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.IMessage, consumer.Consumer) error); ok {
		r0 = rf(messageType, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConnectConsumerHandler provides a mock function with given fields: messageType, consumerHandler
func (_m *ConsumerConnector) ConnectConsumerHandler(messageType types.IMessage, consumerHandler consumer.ConsumerHandler) error {
	ret := _m.Called(messageType, consumerHandler)

	if len(ret) == 0 {
		panic("no return value specified for ConnectConsumerHandler")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.IMessage, consumer.ConsumerHandler) error); ok {
		r0 = rf(messageType, consumerHandler)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewConsumerConnector creates a new instance of ConsumerConnector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConsumerConnector(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConsumerConnector {
	mock := &ConsumerConnector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
