// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ProducerBuilderFuc is an autogenerated mock type for the ProducerBuilderFuc type
type ProducerBuilderFuc[T interface{}] struct {
	mock.Mock
}

// Execute provides a mock function with given fields: builder
func (_m *ProducerBuilderFuc[T]) Execute(builder T) {
	_m.Called(builder)
}

// NewProducerBuilderFuc creates a new instance of ProducerBuilderFuc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProducerBuilderFuc[T interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *ProducerBuilderFuc[T] {
	mock := &ProducerBuilderFuc[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
