// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeOrdersServiceServer is an autogenerated mock type for the UnsafeOrdersServiceServer type
type UnsafeOrdersServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedOrdersServiceServer provides a mock function with given fields:
func (_m *UnsafeOrdersServiceServer) mustEmbedUnimplementedOrdersServiceServer() {
	_m.Called()
}

// NewUnsafeOrdersServiceServer creates a new instance of UnsafeOrdersServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeOrdersServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeOrdersServiceServer {
	mock := &UnsafeOrdersServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
