definitions:
  github_com_zizouhuweidi_retro-station_internal_services_catalogwriteservice_internal_games_dto_v1.GameDto:
    properties:
      createdAt:
        type: string
      description:
        type: string
      gameId:
        type: string
      genre:
        type: string
      name:
        type: string
      price:
        type: number
      updatedAt:
        type: string
    type: object
  ? github_com_zizouhuweidi_retro-station_internal_services_catalogwriteservice_internal_games_features_creating_game_v1_dtos.CreateGameRequestDto
  : properties:
      description:
        type: string
      genre:
        type: string
      name:
        type: string
      price:
        type: number
    type: object
  ? github_com_zizouhuweidi_retro-station_internal_services_catalogwriteservice_internal_games_features_creating_game_v1_dtos.CreateGameResponseDto
  : properties:
      gameId:
        type: string
    type: object
  ? github_com_zizouhuweidi_retro-station_internal_services_catalogwriteservice_internal_games_features_getting_game_by_id_v1_dtos.GetGameByIdResponseDto
  : properties:
      game:
        $ref: '#/definitions/github_com_zizouhuweidi_retro-station_internal_services_catalogwriteservice_internal_games_dto_v1.GameDto'
    type: object
  ? github_com_zizouhuweidi_retro-station_internal_services_catalogwriteservice_internal_games_features_getting_games_v1_dtos.GetGamesResponseDto
  : properties:
      games:
        $ref: '#/definitions/utils.ListResult-github_com_zizouhuweidi_retro-station_internal_services_catalogwriteservice_internal_games_dto_v1_GameDto'
    type: object
  ? github_com_zizouhuweidi_retro-station_internal_services_catalogwriteservice_internal_games_features_searching_game_v1_dtos.SearchGamesResponseDto
  : properties:
      games:
        $ref: '#/definitions/utils.ListResult-github_com_zizouhuweidi_retro-station_internal_services_catalogwriteservice_internal_games_dto_v1_GameDto'
    type: object
  ? github_com_zizouhuweidi_retro-station_internal_services_catalogwriteservice_internal_games_features_updating_game_v1_dtos.UpdateGameRequestDto
  : properties:
      description:
        type: string
      genre:
        type: string
      name:
        type: string
      price:
        type: number
    type: object
  utils.FilterModel:
    properties:
      comparison:
        type: string
      field:
        type: string
      value:
        type: string
    type: object
  utils.ListQuery:
    properties:
      filters:
        items:
          $ref: '#/definitions/utils.FilterModel'
        type: array
      orderBy:
        type: string
      page:
        type: integer
      size:
        type: integer
    type: object
  utils.ListResult-github_com_zizouhuweidi_retro-station_internal_services_catalogwriteservice_internal_games_dto_v1_GameDto:
    properties:
      items:
        items:
          $ref: '#/definitions/github_com_zizouhuweidi_retro-station_internal_services_catalogwriteservice_internal_games_dto_v1.GameDto'
        type: array
      page:
        type: integer
      size:
        type: integer
      totalItems:
        type: integer
      totalPage:
        type: integer
    type: object
info:
  contact:
    name: El Zubeir Huweidi
    url: https://github.com/zizouhuweidi
  description: Catalogs Write-Service Api.
  title: Catalogs Write-Service Api
  version: "1.0"
paths:
  /api/v1/games:
    get:
      consumes:
      - application/json
      description: Get all games
      parameters:
      - in: query
        name: orderBy
        type: string
      - in: query
        name: page
        type: integer
      - in: query
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_zizouhuweidi_retro-station_internal_services_catalogwriteservice_internal_games_features_getting_games_v1_dtos.GetGamesResponseDto'
      summary: Get all game
      tags:
      - Games
    post:
      consumes:
      - application/json
      description: Create new game item
      parameters:
      - description: Game data
        in: body
        name: CreateGameRequestDto
        required: true
        schema:
          $ref: '#/definitions/github_com_zizouhuweidi_retro-station_internal_services_catalogwriteservice_internal_games_features_creating_game_v1_dtos.CreateGameRequestDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_zizouhuweidi_retro-station_internal_services_catalogwriteservice_internal_games_features_creating_game_v1_dtos.CreateGameResponseDto'
      summary: Create game
      tags:
      - Games
  /api/v1/games/{id}:
    delete:
      consumes:
      - application/json
      description: Delete existing game
      parameters:
      - description: Game ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Delete game
      tags:
      - Games
    get:
      consumes:
      - application/json
      description: Get game by id
      parameters:
      - description: Game ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_zizouhuweidi_retro-station_internal_services_catalogwriteservice_internal_games_features_getting_game_by_id_v1_dtos.GetGameByIdResponseDto'
      summary: Get game by id
      tags:
      - Games
    put:
      consumes:
      - application/json
      description: Update existing game
      parameters:
      - description: Game data
        in: body
        name: UpdateGameRequestDto
        required: true
        schema:
          $ref: '#/definitions/github_com_zizouhuweidi_retro-station_internal_services_catalogwriteservice_internal_games_features_updating_game_v1_dtos.UpdateGameRequestDto'
      - description: Game ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Update game
      tags:
      - Games
  /api/v1/games/search:
    get:
      consumes:
      - application/json
      description: Search games
      parameters:
      - in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_zizouhuweidi_retro-station_internal_services_catalogwriteservice_internal_games_features_searching_game_v1_dtos.SearchGamesResponseDto'
      summary: Search games
      tags:
      - Games
swagger: "2.0"
