// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	data "github.com/zizouhuweidi/retro-station/internal/services/catalogwriteservice/internal/games/contracts/data"
)

// CatalogUnitOfWork is an autogenerated mock type for the CatalogUnitOfWork type
type CatalogUnitOfWork struct {
	mock.Mock
}

// Do provides a mock function with given fields: ctx, action
func (_m *CatalogUnitOfWork) Do(ctx context.Context, action data.CatalogUnitOfWorkActionFunc) error {
	ret := _m.Called(ctx, action)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, data.CatalogUnitOfWorkActionFunc) error); ok {
		r0 = rf(ctx, action)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCatalogUnitOfWork creates a new instance of CatalogUnitOfWork. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCatalogUnitOfWork(t interface {
	mock.TestingT
	Cleanup(func())
}) *CatalogUnitOfWork {
	mock := &CatalogUnitOfWork{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
