// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeGamesServiceServer is an autogenerated mock type for the UnsafeGamesServiceServer type
type UnsafeGamesServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedGamesServiceServer provides a mock function with given fields:
func (_m *UnsafeGamesServiceServer) mustEmbedUnimplementedGamesServiceServer() {
	_m.Called()
}

// NewUnsafeGamesServiceServer creates a new instance of UnsafeGamesServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeGamesServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeGamesServiceServer {
	mock := &UnsafeGamesServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
