// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	reflect "reflect"

	mock "github.com/stretchr/testify/mock"

	serializer "github.com/zizouhuweidi/retro-station/internal/pkg/core/serializer"
)

// EventSerializer is an autogenerated mock type for the EventSerializer type
type EventSerializer struct {
	mock.Mock
}

// ContentType provides a mock function with given fields:
func (_m *EventSerializer) ContentType() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ContentType")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Deserialize provides a mock function with given fields: data, eventType, contentType
func (_m *EventSerializer) Deserialize(data []byte, eventType string, contentType string) (interface{}, error) {
	ret := _m.Called(data, eventType, contentType)

	if len(ret) == 0 {
		panic("no return value specified for Deserialize")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte, string, string) (interface{}, error)); ok {
		return rf(data, eventType, contentType)
	}
	if rf, ok := ret.Get(0).(func([]byte, string, string) interface{}); ok {
		r0 = rf(data, eventType, contentType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func([]byte, string, string) error); ok {
		r1 = rf(data, eventType, contentType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeserializeEvent provides a mock function with given fields: data, eventType, contentType
func (_m *EventSerializer) DeserializeEvent(data []byte, eventType string, contentType string) (interface{}, error) {
	ret := _m.Called(data, eventType, contentType)

	if len(ret) == 0 {
		panic("no return value specified for DeserializeEvent")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte, string, string) (interface{}, error)); ok {
		return rf(data, eventType, contentType)
	}
	if rf, ok := ret.Get(0).(func([]byte, string, string) interface{}); ok {
		r0 = rf(data, eventType, contentType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func([]byte, string, string) error); ok {
		r1 = rf(data, eventType, contentType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeserializeMessage provides a mock function with given fields: data, eventType, contentType
func (_m *EventSerializer) DeserializeMessage(data []byte, eventType string, contentType string) (interface{}, error) {
	ret := _m.Called(data, eventType, contentType)

	if len(ret) == 0 {
		panic("no return value specified for DeserializeMessage")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte, string, string) (interface{}, error)); ok {
		return rf(data, eventType, contentType)
	}
	if rf, ok := ret.Get(0).(func([]byte, string, string) interface{}); ok {
		r0 = rf(data, eventType, contentType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func([]byte, string, string) error); ok {
		r1 = rf(data, eventType, contentType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeserializeType provides a mock function with given fields: data, eventType, contentType
func (_m *EventSerializer) DeserializeType(data []byte, eventType reflect.Type, contentType string) (interface{}, error) {
	ret := _m.Called(data, eventType, contentType)

	if len(ret) == 0 {
		panic("no return value specified for DeserializeType")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte, reflect.Type, string) (interface{}, error)); ok {
		return rf(data, eventType, contentType)
	}
	if rf, ok := ret.Get(0).(func([]byte, reflect.Type, string) interface{}); ok {
		r0 = rf(data, eventType, contentType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func([]byte, reflect.Type, string) error); ok {
		r1 = rf(data, eventType, contentType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Serialize provides a mock function with given fields: event
func (_m *EventSerializer) Serialize(event interface{}) (*serializer.EventSerializationResult, error) {
	ret := _m.Called(event)

	if len(ret) == 0 {
		panic("no return value specified for Serialize")
	}

	var r0 *serializer.EventSerializationResult
	var r1 error
	if rf, ok := ret.Get(0).(func(interface{}) (*serializer.EventSerializationResult, error)); ok {
		return rf(event)
	}
	if rf, ok := ret.Get(0).(func(interface{}) *serializer.EventSerializationResult); ok {
		r0 = rf(event)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serializer.EventSerializationResult)
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(event)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Serializer provides a mock function with given fields:
func (_m *EventSerializer) Serializer() serializer.Serializer {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Serializer")
	}

	var r0 serializer.Serializer
	if rf, ok := ret.Get(0).(func() serializer.Serializer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(serializer.Serializer)
		}
	}

	return r0
}

// NewEventSerializer creates a new instance of EventSerializer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventSerializer(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventSerializer {
	mock := &EventSerializer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
