// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	domain "github.com/zizouhuweidi/retro-station/internal/pkg/core/domain"

	time "time"

	uuid "github.com/satori/go.uuid"
)

// IDomainEvent is an autogenerated mock type for the IDomainEvent type
type IDomainEvent struct {
	mock.Mock
}

// GetAggregateId provides a mock function with given fields:
func (_m *IDomainEvent) GetAggregateId() uuid.UUID {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAggregateId")
	}

	var r0 uuid.UUID
	if rf, ok := ret.Get(0).(func() uuid.UUID); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	return r0
}

// GetAggregateSequenceNumber provides a mock function with given fields:
func (_m *IDomainEvent) GetAggregateSequenceNumber() int64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAggregateSequenceNumber")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// GetEventId provides a mock function with given fields:
func (_m *IDomainEvent) GetEventId() uuid.UUID {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEventId")
	}

	var r0 uuid.UUID
	if rf, ok := ret.Get(0).(func() uuid.UUID); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	return r0
}

// GetEventType provides a mock function with given fields:
func (_m *IDomainEvent) GetEventType() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEventType")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetOccurredOn provides a mock function with given fields:
func (_m *IDomainEvent) GetOccurredOn() time.Time {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetOccurredOn")
	}

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// WithAggregate provides a mock function with given fields: aggregateId, aggregateSequenceNumber
func (_m *IDomainEvent) WithAggregate(aggregateId uuid.UUID, aggregateSequenceNumber int64) *domain.DomainEvent {
	ret := _m.Called(aggregateId, aggregateSequenceNumber)

	if len(ret) == 0 {
		panic("no return value specified for WithAggregate")
	}

	var r0 *domain.DomainEvent
	if rf, ok := ret.Get(0).(func(uuid.UUID, int64) *domain.DomainEvent); ok {
		r0 = rf(aggregateId, aggregateSequenceNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.DomainEvent)
		}
	}

	return r0
}

// NewIDomainEvent creates a new instance of IDomainEvent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIDomainEvent(t interface {
	mock.TestingT
	Cleanup(func())
}) *IDomainEvent {
	mock := &IDomainEvent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
