// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Serializer is an autogenerated mock type for the Serializer type
type Serializer struct {
	mock.Mock
}

// ColoredPrettyPrint provides a mock function with given fields: data
func (_m *Serializer) ColoredPrettyPrint(data interface{}) string {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for ColoredPrettyPrint")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(interface{}) string); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// DecodeWithMapStructure provides a mock function with given fields: input, output
func (_m *Serializer) DecodeWithMapStructure(input interface{}, output interface{}) error {
	ret := _m.Called(input, output)

	if len(ret) == 0 {
		panic("no return value specified for DecodeWithMapStructure")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, interface{}) error); ok {
		r0 = rf(input, output)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Marshal provides a mock function with given fields: v
func (_m *Serializer) Marshal(v interface{}) ([]byte, error) {
	ret := _m.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for Marshal")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(interface{}) ([]byte, error)); ok {
		return rf(v)
	}
	if rf, ok := ret.Get(0).(func(interface{}) []byte); ok {
		r0 = rf(v)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(v)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PrettyPrint provides a mock function with given fields: data
func (_m *Serializer) PrettyPrint(data interface{}) string {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for PrettyPrint")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(interface{}) string); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Unmarshal provides a mock function with given fields: data, v
func (_m *Serializer) Unmarshal(data []byte, v interface{}) error {
	ret := _m.Called(data, v)

	if len(ret) == 0 {
		panic("no return value specified for Unmarshal")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte, interface{}) error); ok {
		r0 = rf(data, v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UnmarshalFromJson provides a mock function with given fields: data, v
func (_m *Serializer) UnmarshalFromJson(data string, v interface{}) error {
	ret := _m.Called(data, v)

	if len(ret) == 0 {
		panic("no return value specified for UnmarshalFromJson")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}) error); ok {
		r0 = rf(data, v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UnmarshalToMap provides a mock function with given fields: data, v
func (_m *Serializer) UnmarshalToMap(data []byte, v *map[string]interface{}) error {
	ret := _m.Called(data, v)

	if len(ret) == 0 {
		panic("no return value specified for UnmarshalToMap")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte, *map[string]interface{}) error); ok {
		r0 = rf(data, v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UnmarshalToMapFromJson provides a mock function with given fields: data, v
func (_m *Serializer) UnmarshalToMapFromJson(data string, v *map[string]interface{}) error {
	ret := _m.Called(data, v)

	if len(ret) == 0 {
		panic("no return value specified for UnmarshalToMapFromJson")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *map[string]interface{}) error); ok {
		r0 = rf(data, v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSerializer creates a new instance of Serializer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSerializer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Serializer {
	mock := &Serializer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
