// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Specification is an autogenerated mock type for the Specification type
type Specification struct {
	mock.Mock
}

// GetQuery provides a mock function with given fields:
func (_m *Specification) GetQuery() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetQuery")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetValues provides a mock function with given fields:
func (_m *Specification) GetValues() []interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetValues")
	}

	var r0 []interface{}
	if rf, ok := ret.Get(0).(func() []interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interface{})
		}
	}

	return r0
}

// NewSpecification creates a new instance of Specification. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSpecification(t interface {
	mock.TestingT
	Cleanup(func())
}) *Specification {
	mock := &Specification{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
