// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	domain "github.com/zizouhuweidi/retro-station/internal/pkg/core/domain"
)

// WhenFunc is an autogenerated mock type for the WhenFunc type
type WhenFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: event
func (_m *WhenFunc) Execute(event domain.IDomainEvent) error {
	ret := _m.Called(event)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.IDomainEvent) error); ok {
		r0 = rf(event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewWhenFunc creates a new instance of WhenFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWhenFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *WhenFunc {
	mock := &WhenFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
